# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
      redirectListenner:
          class: Annonce\MainBundle\Listenner\RedirectionListenner
          arguments: ["@service_container","@session"]
          tags:
              - { name: kernel.event_listener, event: kernel.request ,method: onKernelRequest }