<?php

namespace Annonce\MainBundle\Repository;

/**
 * SousCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousCategoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
