<?php

namespace Annonce\UserBundle\Repository;

/**
 * NothificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NothificationRepository extends \Doctrine\ORM\EntityRepository
{
}
