admin_annonce_index:
    path:     /
    defaults: { _controller: "AnnonceMainBundle:Annonce:index" }
    methods:  GET

admin_annonce_show:
    path:     /{id}/show
    defaults: { _controller: "AnnonceMainBundle:Annonce:show" }
    methods:  GET

admin_annonce_new:
    path:     /new
    defaults: { _controller: "AnnonceMainBundle:Annonce:new" }
    methods:  [GET, POST]

admin_annonce_edit:
    path:     /{id}/edit
    defaults: { _controller: "AnnonceMainBundle:Annonce:edit" }
    methods:  [GET, POST]

admin_annonce_delete:
    path:     /{id}/delete
    defaults: { _controller: "AnnonceMainBundle:Annonce:delete" }
    methods:  DELETE
