admin_categories_index:
    path:     /
    defaults: { _controller: "AnnonceMainBundle:Categories:index" }
    methods:  GET

admin_categories_new:
    path:     /new
    defaults: { _controller: "AnnonceMainBundle:Categories:new" }
    methods:  [GET, POST]

admin_categories_edit:
    path:     /edit/{id}
    defaults: { _controller: "AnnonceMainBundle:Categories:edit" }
    methods:  [GET, POST]

admin_categories_delete:
    path:     /delete/{id}
    defaults: { _controller: "AnnonceMainBundle:Categories:delete" }
